G_SHEET: "https://sheets.googleapis.com/v4/spreadsheets/1Vue0K22AEzZrWxndFAO-iCxmT8CLtb0YpJMq_RDX8AA"
API_KEY: "AIzaSyBLySbKUYIzPNpscruuGrSpnA3VeZ1sdvk"
metaTitle: "Imre Mehesz - Standup Comedian"
metaDescription: "This is a meta descriotion"
metaKeywords: "Imre Mehesz, Comedian, Comedy, Comedy Show, Comedy Workshop, Comedy Writing, Standup, Standup Comedy, Stand-up, open mic"
metaCanonicalUrl: "https://IMstandup.com"
metaOgTitle: "Imre Mehesz - Comedian"
metaOgDescription: "This is a meta descriotion"
metaOgUrl: "https://IMstandup.com"
metaOgType: "website"
metaOgImage: "https://i.imgur.com/ZyTab4O.png"
metaTwitterCard: "summary"
metaTwitterTitle: "Imre Mehesz - Comedian"
metaTwitterDescription: "This is a meta descriotion"
metaTwitterImage: "https://i.imgur.com/ZyTab4O.png"